const dados = [
  { produto: "Vulnerability Manager Plus", edicao: "Enterprise", horas: 10, caminho: "Vulnerability Manager Plus/Vulnerability Manager Plus - Enterprise.docx" },
  { produto: "Vulnerability Manager Plus", edicao: "Professional", horas: 8 },
  { produto: "Application Control Plus", edicao: "Professional", horas: 8 },
  { produto: "DeviceControl Plus", edicao: "Professional", horas: 8 },
  { produto: "Endpoint DLP Plus", edicao: "Professional", horas: 10 },
  { produto: "Browser Security Plus", edicao: "Profesisonal", horas: 8 },
  { produto: "MDM Cloud", edicao: "Professional", horas: 12 },
  { produto: "MDM On-Premise", edicao: "Standard", horas: 14 },
  { produto: "MDM On-Premise", edicao: "Professional", horas: 20 },
  { produto: "MDM On-Premise", edicao: "Enterprise", horas: 24 },
  { produto: "MDM Cloud", edicao: "Standard", horas: 8 },
  { produto: "MDM Cloud", edicao: "Enterprise", horas: 16 },
  { produto: "Mobile Device Manager Plus", edicao: "Standard", horas: 8 },
  { produto: "Mobile Device Manager Plus", edicao: "Professional", horas: 12 },
  { produto: "Mobile Device Manager Plus", edicao: "Enterprise", horas: 16 },
  { produto: "Endpoint Central Plus On-Premise", edicao: "Enterprise", horas: 14 },
  { produto: "Endpoint Central Plus On-Premise", edicao: "Professional", horas: 12 },
  { produto: "Endpoint Central Plus On-Premise", edicao: "Security", horas: 24 },
  { produto: "Endpoint Central Plus Cloud", edicao: "Enterprise", horas: 12 },
  { produto: "Endpoint Central Plus Cloud", edicao: "UEM", horas: 12 },
  { produto: "Endpoint Central Plus Cloud", edicao: "Security", horas: 24 },
  { produto: "Endpoint Central Cloud", edicao: "Enterprise", horas: 12 },
  { produto: "Endpoint Central Cloud", edicao: "UEM", horas: 12 },
  { produto: "Endpoint Central Cloud", edicao: "Security", horas: 24 },
  { produto: "Endpoint Central On-Premise", edicao: "Enterprise", horas: 14 },
  { produto: "Endpoint Central On-Premise", edicao: "Professional", horas: 12 },
  { produto: "Endpoint Central On-Premise", edicao: "Security", horas: 24 },
  { produto: "OpManager", edicao: "Standard", horas: 10 },
  { produto: "OpManager", edicao: "Professional", horas: 16 },
  { produto: "OpManager", edicao: "Enterprise", horas: 20 },
  { produto: "OpManager Plus", edicao: "Enterprise", horas: 24 },
  { produto: "OpManager MSP", edicao: "Enterprise", horas: 24 },
  { produto: "OpManager Plus", edicao: "MSP", horas: 24 },
  { produto: "OpManager MSP", edicao: "MSP", horas: 24 },
  { produto: "OpManager Plus", edicao: "Professional", horas: 20 },
  { produto: "OpManager MSP", edicao: "Professional", horas: 20 },
  { produto: "OpManager Plus", edicao: "Standard", horas: 14 },
  { produto: "OpManager MSP", edicao: "Standard", horas: 14 },
  { produto: "Applications Manager", edicao: "Professional", horas: 14 },
  { produto: "Applications Manager", edicao: "Enterprise", horas: 16 },
  { produto: "Site24x7", edicao: "Enterprise", horas: 14 },
  { produto: "ServiceDesk Plus", edicao: "Standard", horas: 12 },
  { produto: "ServiceDesk Plus", edicao: "Professional", horas: 18 },
  { produto: "ServiceDesk Plus", edicao: "Enterprise", horas: 30 },
  { produto: "ServiceDesk Plus MSP", edicao: "Standard", horas: 12 },
  { produto: "ServiceDesk Plus MSP", edicao: "Professional", horas: 18 },
  { produto: "ServiceDesk Plus MSP", edicao: "Enterprise", horas: 30 },
  { produto: "ServiceDesk Plus Cloud", edicao: "Standard", horas: 12 },
  { produto: "ServiceDesk Plus Cloud", edicao: "Professional", horas: 18 },
  { produto: "ServiceDesk Plus Cloud", edicao: "Enterprise", horas: 30 },
  { produto: "ADManager Plus", edicao: "Standard", horas: 10 },
  { produto: "ADManager Plus", edicao: "Professional", horas: 14 },
  { produto: "ADManager Plus", edicao: "Enterprise", horas: 16 },
  { produto: "ADSelfService Plus", edicao: "Standard", horas: 10 },
  { produto: "ADSelfService Plus", edicao: "Professional", horas: 12 },
  { produto: "ADSelfService Plus", edicao: "Enterprise", horas: 14 },
  { produto: "Analytics Plus", edicao: "Professional", horas: 14 },
  { produto: "Analytics Plus", edicao: "Enterprise", horas: 16 },
  { produto: "GO-Global", edicao: "-", horas: 2 },
];